# Generated by Django 5.2.8 on 2025-11-25 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careapp', '0002_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('dermatology', 'Dermatology'), ('internal-medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('emergency', 'Emergency Medicine')], max_length=50)),
                ('preferred_doctor', models.CharField(blank=True, choices=[('', 'Any Available Doctor'), ('dr-johnson', 'Dr. Sarah Johnson (Cardiology)'), ('dr-chen', 'Dr. Michael Chen (Neurology)'), ('dr-rodriguez', 'Dr. Emily Rodriguez (Internal Medicine)'), ('dr-wilson', 'Dr. James Wilson (Orthopedics)'), ('dr-jepson', 'Dr. Amanda Jepson (Pediatrics)')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('08:00', '8:00 AM'), ('08:30', '8:30 AM'), ('09:00', '9:00 AM'), ('09:30', '9:30 AM'), ('10:00', '10:00 AM'), ('10:30', '10:30 AM'), ('11:00', '11:00 AM'), ('11:30', '11:30 AM'), ('13:00', '1:00 PM'), ('13:30', '1:30 PM'), ('14:00', '2:00 PM'), ('14:30', '2:30 PM'), ('15:00', '3:00 PM'), ('15:30', '3:30 PM'), ('16:00', '4:00 PM'), ('16:30', '4:30 PM')], max_length=5)),
                ('appointment_type', models.CharField(choices=[('consultation', 'New Patient Consultation'), ('follow-up', 'Follow-up Visit'), ('routine-checkup', 'Routine Check-up'), ('emergency', 'Emergency Visit'), ('telemedicine', 'Telemedicine Consultation'), ('procedure', 'Medical Procedure')], max_length=20)),
                ('reason_for_visit', models.TextField()),
                ('current_symptoms', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_id', models.CharField(blank=True, max_length=50)),
                ('terms_accepted', models.BooleanField()),
                ('communication_consent', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the appointment')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
