# Generated by Django 5.2.8 on 2025-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careapp', '0004_appoinment_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment_index',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
