# Generated by Django 5.2.8 on 2025-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Careapp', '0005_alter_appoinment_index_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactFirstName', models.CharField(max_length=20)),
                ('contactLastName', models.CharField(max_length=20)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhone', models.CharField(max_length=15)),
                ('contactMessage', models.TextField()),
                ('contactDepartment', models.CharField(max_length=50)),
                ('contactSubject', models.CharField(max_length=100)),
            ],
        ),
    ]
